config/routes.rb
# Routes
# Team 1
# Author: Meagan Moore

Rails.application.routes.draw do
  root "login_session#new"
  
  get "teachers/:id/home",  to: 'teachers#home'

  resources :roster_students
  resources :roster_squares
  resources :session_events
  resources :sessions
  resources :squares
  resources :students
  resources :teachers
  resources :schools
  resources :login_session

  get    'login'   => 'login_session#new'
  post   'login'   => 'login_session#create'
  
  get    'logout'  => 'login_session#logout'
  
  get    'about1'  => 'static_pages#about1'
  get    'about2'  => 'static_pages#about2'
  
  get    'home1'   => 'static_pages#home1'
  post   'home1'   => 'static_pages#home1'

  resources :super
  get    '/super_report',    to: 'teachers#super_report'
  get    '/admin',    to: 'teachers#admin'
  #go back and make /super show the dashboard NOT /schools ... fix later.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roster_square.rb
class RosterSquare < ApplicationRecord
  belongs_to :student, class_name: "Student"
  belongs_to :square, class_name: "Square"
end

app/controllers/roster_squares_controller.rb
class RosterSquaresController < ApplicationController
  before_action :set_roster_square, only: [:show, :edit, :update, :destroy]

  # GET /roster_squares
  # GET /roster_squares.json
  def index
    @roster_squares = RosterSquare.all
  end

  # GET /roster_squares/1
  # GET /roster_squares/1.json
  def show
  end

  # GET /roster_squares/new
  def new
    @roster_square = RosterSquare.new
  end

  # GET /roster_squares/1/edit
  def edit
  end

  # POST /roster_squares
  # POST /roster_squares.json
  def create
    @roster_square = RosterSquare.new(roster_square_params)

    respond_to do |format|
      if @roster_square.save
        format.html { redirect_to @roster_square, notice: 'Roster square was successfully created.' }
        format.json { render :show, status: :created, location: @roster_square }
      else
        format.html { render :new }
        format.json { render json: @roster_square.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roster_squares/1
  # PATCH/PUT /roster_squares/1.json
  def update
    respond_to do |format|
      if @roster_square.update(roster_square_params)
        format.html { redirect_to @roster_square, notice: 'Roster square was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster_square }
      else
        format.html { render :edit }
        format.json { render json: @roster_square.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roster_squares/1
  # DELETE /roster_squares/1.json
  def destroy
    @roster_square.destroy
    respond_to do |format|
      format.html { redirect_to roster_squares_url, notice: 'Roster square was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster_square
      @roster_square = RosterSquare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_square_params
      params.require(:roster_square).permit(:square_id, :student_id)
    end
end

app/helpers/roster_squares_helper.rb
module RosterSquaresHelper
end

app/views/roster_squares/_form.html.erb
<%= form_for(roster_square) do |f| %>
  <% if roster_square.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roster_square.errors.count, "error") %> prohibited this roster_square from being saved:</h2>

      <ul>
      <% roster_square.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :square_id %>
    <%= f.number_field :square_id %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.number_field :student_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roster_squares/edit.html.erb
<h1>Editing Roster Square</h1>

<%= render 'form', roster_square: @roster_square %>

<%= link_to 'Show', @roster_square %> |
<%= link_to 'Back', roster_squares_path %>

app/views/roster_squares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roster Squares</h1>

<table>
  <thead>
    <tr>
      <th>Square</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roster_squares.each do |roster_square| %>
      <tr>
        <td><%= roster_square.square_id %></td>
        <td><%= roster_square.student_id %></td>
        <td><%= link_to 'Show', roster_square %></td>
        <td><%= link_to 'Edit', edit_roster_square_path(roster_square) %></td>
        <td><%= link_to 'Destroy', roster_square, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster Square', new_roster_square_path %>

app/views/roster_squares/new.html.erb
<h1>New Roster Square</h1>

<%= render 'form', roster_square: @roster_square %>

<%= link_to 'Back', roster_squares_path %>

app/views/roster_squares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Square:</strong>
  <%= @roster_square.square_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @roster_square.student_id %>
</p>

<%= link_to 'Edit', edit_roster_square_path(@roster_square) %> |
<%= link_to 'Back', roster_squares_path %>