config/routes.rb
# Routes
# Team 1
# Author: Meagan Moore

Rails.application.routes.draw do
  root "login_session#new"
  
  get "teachers/:id/home",  to: 'teachers#home'

  resources :roster_students
  resources :roster_squares
  resources :session_events
  resources :sessions
  resources :squares
  resources :students
  resources :teachers
  resources :schools
  resources :login_session

  get    'login'   => 'login_session#new'
  post   'login'   => 'login_session#create'
  
  get    'logout'  => 'login_session#logout'
  
  get    'about1'  => 'static_pages#about1'
  get    'about2'  => 'static_pages#about2'
  
  get    'home1'   => 'static_pages#home1'
  post   'home1'   => 'static_pages#home1'

  resources :super
  get    '/super_report',    to: 'teachers#super_report'
  get    '/admin',    to: 'teachers#admin'
  #go back and make /super show the dashboard NOT /schools ... fix later.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
#author: Tommy Banas

#extra notes for Tommy B:
#   rails server -b $IP -p $PORT

class Teacher < ApplicationRecord
  
  # Create an accessible attribute
  # author: Meagan Moore
  attr_accessor :remember_token
  
  validates :user_name,  presence: true, length: { maximum: 75 }
  validates :teacher_icon_name,  presence: true, length: { maximum: 15 }
  validates :teacher_name, presence: true, length: { maximum: 75 }
  validates :teacher_email, presence: true, length: { maximum: 255 }
  validates :teacher_description, presence: true
  validates :color, presence: true
  validates :teacher_password, presence: true, length: { minimum: 6 }, allow_nil: true
  # the password confirmation is not implemented
  #validates :teacher_password_confirmation, presence: true, length: { minimum: 6 }, allow_nil: true


  #Creates the relationship of what students belong to the teacher
  #author Matthew OBzera
  has_many :active_relationships, class_name:  "RosterStudent",
                                  foreign_key: "teacher_id",
                                  dependent:   :destroy

  has_many :students, through: :active_relationships, source: :student
  
  # Returns the hash digest of the given string.
  # author: Meagan Moore
  def Teacher.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token for remembering users
  # author: Meagan Moore
  def Teacher.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a teacher in the database for use in persistent sessions.
  # author: Meagan Moore
  def remember
    self.remember_token = Teacher.new_token
    update_attribute(:remember_digest, Teacher.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  # author: Meagan Moore
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
end

app/controllers/teachers_controller.rb
#extra notes for Tommy B:
#   rails server -b $IP -p $PORT

# author: Tommy B
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])
  end
  
  #author: Matthew O
  def home
    @teacher = Teacher.find(params[:id])
    @top_students = Student.where(id: Session.where(session_teacher: @teacher.id).group('session_student').order('count(*)').select('session_student').limit(8))
    if params[:start_session]
        @session = Session.new
        @session.session_teacher = @teacher.id
        @session.session_student = params[:student_id]
        @session.start_time = Time.now
        respond_to do |format|
          if @session.save
            format.html { redirect_to @session, notice: 'Session was successfully created.' }
            format.json { render :show, status: :created, location: @session }
          else
            format.html { render :new }
            format.json { render json: @session.errors, status: :unprocessable_entity }
          end
        end
    elsif params[:analyze]
        # Currently unimplemented will direct to analysis page for the selected student
    end
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:user_name, :teacher_icon_name, :teacher_name, :teacher_email, :admin_powers, :analysis_powers, :teacher_description, :color, :school_id, :teacher_password, :teacher_password_confirmation)
    end
    
      # RH
      # Confirms an admin user.
    def admin_user
        redirect_to(root_url) unless current_user.admin_powers?
    end
    
end

app/helpers/teachers_helper.rb
#extra notes for Tommy B:
#   rails server -b $IP -p $PORT

# author: Tommy B

module TeachersHelper
end

app/views/teachers/_form.html.erb
<!-- Note from Tommy B: please don't edit this file! -->
<!-- Note from Tommy B: please don't edit this file! -->
<!-- Note from Tommy B: please don't edit this file! -->
<!-- Note from Tommy B: please don't edit this file! -->

<%= form_for(teacher) do |f| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :teacher_icon_name %>
    <%= f.text_field :teacher_icon_name %>
  </div>
  <div class="field">
    <%= f.label :teacher_name %>
    <%= f.text_field :teacher_name %>
  </div>
  <div class="field">
    <%= f.label :teacher_email %>
    <%= f.text_field :teacher_email %>
  </div>
  <div class="field">
    <%= f.label :admin_powers %>
    <%= f.check_box :admin_powers %>
  </div>
  <div class="field">
    <%= f.label :analysis_powers %>
    <%= f.check_box :analysis_powers %>
  </div>
  <div class="field">
    <%= f.label :teacher_description %>
    <%= f.text_area :teacher_description %>
  </div>
  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :school_id %>
    <%= f.number_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :teacher_password %>
    <%= f.text_field :teacher_password %>
  </div>
  <div class="field">
    <%= f.label :teacher_password_confirmation %>
    <%= f.text_field :teacher_password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/admin.html.erb
<!-- Robert Herrera changes-->

<!-- page header -->
<div class="page-header vertical-align">
	<div class="col-xs-11">
		<h2>Admin Dashboard<small> - manage school TPTE</small></h2><!-- Dynamically fills in with school id -->
	</div>
		<div class="col-xs-1 center-block">
			<div class="header-sq i-plum" title="Bianca17">
				<span class="fa fa-apple fa-3x teacher-icon"></span>
			</div>
		</div>
</div><!--End page header-->

<!-- Will use current_user to create dynamic links -->
<div class="header-sq i-ltblue" title="Turning Pointe Autism Foundation"> <!--Need to add code for teachers icon-->
	<span class="fa fa-home fa-3x teacher-icon"></span>
</div>
<div>
<form action='schools/2'>
	<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"></span> 
	School Profile</button>
</form>

<div class="header-sq i-ltblue" title="Turning Pointe Autism Foundation"> <!--Need to add code for teachers icon-->
</div>
<form action='students'>
	<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"></span>  
	All Students</button>
</form>
<div class="header-sq i-ltblue" title="Turning Pointe Autism Foundation"> <!--Need to add code for teachers icon-->
	<span class="fa fa-home fa-3x teacher-icon"></span>
</div>

<form action='teachers'>
	<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"></span>  
	All Teachers</button>
</form>

<div class="header-sq i-ltblue" title="Turning Pointe Autism Foundation"> <!--Need to add code for teachers icon-->
	<span class="fa fa-home fa-3x students-icon"></span>
</div>
<form action='squares'>
	<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"></span>  
	All Squares</button>
</form>

<div class="header-sq i-ltblue" title="Turning Pointe Autism Foundation"> <!--Need to add code for teachers icon-->
	<span class="fa fa-home fa-3x students-icon"></span>
</div>
<form action='students/show'>
	<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"></span>  
	Admin Report</button>
</form>

app/views/teachers/edit.html.erb
<!-- NEED TO PROPERLY LINK TO SHOW ROSTER AND CHANGE PASSWORD -->

<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="page-header cap17-header vertical-align">
				<div class="col-xs-11">
					<h2>Teacher Profile for <%= @teacher.teacher_name %></h2>
				</div>
				<div class="col-xs-1">
					<div class="profile-sq i-<%= @teacher.color %>" >
						<span class="fa fa-<%= @teacher.teacher_icon_name %> fa-3x teacher-icon "></span>
					</div>
				</div>
	</div><!--End page-header-->
	
	<!--School profile area -->
	<!--<form class="form-horizontal" action="teacher1.html">-->
	
		 	<!--ID & Name -->
		 	<div class="row form-row">
				<div class="col-xs-2 col-xs-offset-1"><h4> Teacher ID: </h4></div>
				<div class="col-xs-2">
					<%= f.text_field :user_name %>
				</div>
			</div>
			
			<!-- Teacher Name Field -->
    	<div class="row form-row">
        <div class="col-xs-1 col-xs-offset-1"><h4> Name: </h4></div>
       		<div class="col-xs-4 col-xs-offset-1">
    			<%= f.text_field :teacher_name %>
    		</div>
    	</div>   <!-- row -->
    	
    	<!-- Email -->
			<div class="row form-row">
				<div class="col-xs-2 col-xs-offset-1"><h4> Email: </h4></div>
				<div class="col-xs-4">
					<%= f.text_field :teacher_email %>
				</div>
			</div>
			
			<!-- a little extra space after name/email -->
			<div class="form-spacer">	&nbsp;</div>
			
			<!-- Admin field -->
			<div class="row form-row">
				<div class="col-xs-2 col-xs-offset-1"><h4> Admin: </h4></div>
				<div class="col-xs-4">
					<%= f.check_box :admin_powers %>
				</div>
			</div>
			
			<!-- Teacher color field -->
			<div class="row form-row">
				<div class="col-xs-2 col-xs-offset-1"><h4> Color: </h4></div>
				<div class="col-xs-4">
					<%= f.select :color, [ 'plum', 'red', 'yellow', 'cyan'] %>
				</div>
		 	</div>
		 	
		 	<!-- Teacher icon field -->
			<div class="row form-row">
				<div class="col-xs-1 col-xs-offset-1"><h4> Icon: </h4></div>
				<div class="col-xs-4 col-xs-offset-1">
					<%= f.select :teacher_icon_name, [ 'apple', 'graduationHat', 'book', 'pencil'] %>
				</div>
			</div>
			
			<!-- Teacher Description Field -->
			<div class="row form-row">
				<div class="col-xs-2 col-xs-offset-1"><h4>Description: </h4></div>
				<div class="col-xs-6">
					<%= f.text_area :teacher_description %>
				</div>
			</div>
				
			<div class="row action-buttons-row">
    			<div class="col-sm-1 col-sm-offset-1">
    				<%= f.submit %>
    			</div>
    			<div class="col-sm-1 col-sm-offset-1">
    				<%= link_to 'Cancel', teachers_path %>
    			</div>
  		</div>
<% end %>

    <!--Action Icons -->
		<div class="row action-icon-row" style="margin-top: 40px;">
			<div class="col-xs-2 col-xs-offset-1 text-center" title="Student Roster">
				<div class ="action-sq i-red center-block">
					<%= link_to 'Show', @teacher %><span class="fa fa-child fa-4x student-icon"></span></a>
				</div>
				<p><%= link_to 'Show', @teacher %><span class="student-icon-text"> Student Roster</span></a></p>
			</div>
			<div class="col-xs-2 col-xs-offset-1 text-center" title="Change Password">
				<div class ="action-sq i-navy center-block">
					<%= link_to '', @teacher %><span class="fa fa-key fa-4x student-icon"></span></a>
				</div>
				<p><%= link_to '', @teacher %><span class="student-icon-text">Change Password</span></a></p>
			</div>
		</div>

app/views/teachers/home.html.erb
<!-- @author: Matthew O & Alex P -->
<!-- page header -->
<div class="page-header vertical-align">
	<div class="col-xs-11">
		<h2>Home<small> - student roster for teacher <%= @teacher.teacher_icon_name %></small></h2><!-- Dynamically fills in with school id -->
	</div>
	<div class="col-xs-1 pull-right">
		<div class="header-sq i-plum" >
			<span class="fa fa-apple fa-3x teacher-icon"></span>
		</div>
	</div>
</div><!--End page header-->

<!--Student Roster Area -->
<div id="student-roster"> <!--Student display area: shows the last 8 students teacher worked with -->
	<% @top_students.each_with_index do |student, index| %>
		<% if index == 0 || index == 4 %>
			<div class="row students-row">
		<% end %>
		<div class="col-xs-3 text-center">
      <div class =" square i-<%= student.color %> center-block">
          <span class="fa fa-<%= student.student_icon %> fa-5x student-icon "></span>
      </div>
      <p><span class="student-icon-text"><%= student.student_name%></span></p>
    </div>    <!-- col -->
    <% if index == 3 || index == 7 || index == (@top_students.size-1) %>
    	</div>   <!-- row -->
    <% end %>
  <% end %>
</div> <!--End Student Roster -->
<!-- Search Form should populate with student name on selection -->
<!-- All students who are assigned to teacher will populate here -->
<!-- horizontal form help from:	www.w3schools.com/bootstrap/bootstrap_forms.asp -->
<div class="row">
	<form class="form-horizontal text-center action-buttons-row">
		<div class="col-sm-offset-3">
			<div class="form-group">
				<label class="control-label col-sm-2" for="email">Student:</label>
				<div class="col-sm-4">
					<%= select_tag 'student_id', options_from_collection_for_select(@teacher.students, 'id', 'student_name'), {:required => true} %>
				</div>
			</div>
		</div>
		<div class="form-group"> 
			<div class="col-xs-3 text-center col-xs-offset-3">
				<%= button_tag(type: 'submit', class: "btn btn-lg btn-primary", name: 'start_session') do %>
					<i class="fa fa-clock-o"></i>  Start Session
				<% end %>
			</div>
			<div class="col-xs-3 text-center">
				<%= button_tag(type: 'submit', class: "btn btn-lg btn-success", name: 'analyze') do %>
					<i class="fa fa-line-chart"></i> Analyze Sessions
				<% end %>
			</div>
		</div>
	</form>
</div>   <!-- row -->

app/views/teachers/index.html.erb
<!-- NEED TO ADD IMPLEMENTATION FOR TEACHER ICONS/TEACHER SHORT AND FULL NAMES -->

<p id="notice"><%= notice %></p>

<!-- page header -->
		<div class="page-header vertical-align">
			<div class="col-xs-11">
				<h2>All Teachers<small> - manage teachers at TPTE</small></h2><!-- Dynamically fills in with school id -->
			</div>
			<div class="col-xs-1 center-block">
				<div class="header-sq i-plum" title="Bianca17">
					<span class="fa fa-apple fa-3x teacher-icon"></span>
				</div>
			</div>
		</div><!--End page header-->
   
		<!--New Teacher Button-->
    <div class="row first-content-row">
    	<div class="col-xs-3">
			<form action='teachers/new'>
				<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"><i class="fa fa-plus-square-o"></i>  
				New Teacher</button>
			</form>
		</div><!--End col-->
    </div><!--End row -->
    
    
    
    
   	 <!--Teacher display area -->
   	<table class="table table-striped table-hover table-responsive teachers-table">
   		<thead>
   			<tr>
				  <th class="col-xs-1">Icon</th>
				  <th>ID</th>
				  <th>Name</th>
				  <th>Admin</th>
				  <th>Last Login</th>
			</tr>
		</thead>
		<tbody>
		  <% @teachers.each do |teacher| %>
		  <tr>
				<td>
					<div class="table-sq i-<%= teacher.color %>">
						<span class="fa fa-<%= teacher.teacher_icon_name %> fa-2x table-icon"></span>
					</div>
				</td>
				<td><%= teacher.user_name %></td>
				<td><%= teacher.teacher_name %></td>
				<td><%= teacher.admin_powers %></td>
				<td><p class="listText"><span>FILL IN PROPER DATE</span></p></td>
      </tr>
      <% end %>
    </tbody>
    </thead>

app/views/teachers/index.html_BASE_2089.erb
<!-- NEED TO ADD IMPLEMENTATION FOR TEACHER ICONS/TEACHER SHORT AND FULL NAMES -->

<p id="notice"><%= notice %></p>

<<<<<<< HEAD
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.user_name %></td>
        <td><%= teacher.teacher_icon_name %></td>
        <td><%= teacher.teacher_name %></td>
        <td><%= teacher.teacher_email %></td>
        <td><%= teacher.admin_powers %></td>
        <td><%= teacher.analysis_powers %></td>
        <td><%= teacher.teacher_description %></td>
        <td><%= teacher.color %></td>
        <td><%= teacher.school_id %></td>
        <td><%= teacher.teacher_password %></td>
        <td><%= teacher.teacher_password_confirmation %></td>
        <td>Super ID: <%= teacher.super_id %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
=======
<!-- page header -->
		<div class="page-header vertical-align">
			<div class="col-xs-11">
				<h2>All Teachers<small> - manage teachers at TPTE</small></h2><!-- Dynamically fills in with school id -->
			</div>
			<div class="col-xs-1 center-block">
				<div class="header-sq i-plum" title="Bianca17">
					<span class="fa fa-apple fa-3x teacher-icon"></span>
				</div>
			</div>
		</div><!--End page header-->
   
		<!--New Teacher Button-->
    <div class="row first-content-row">
    	<div class="col-xs-3">
			<form action='teachers/new'>
				<button type="submit" class="col-sm-offset-1 btn btn-lg btn-success"><i class="fa fa-plus-square-o"></i>  
				New Teacher</button>
			</form>
		</div><!--End col-->
    </div><!--End row -->
    
    
    
    
   	 <!--Teacher display area -->
   	<table class="table table-striped table-hover table-responsive teachers-table">
   		<thead>
   			<tr>
				  <th class="col-xs-1">Icon</th>
				  <th>ID</th>
				  <th>Name</th>
				  <th>Admin</th>
				  <th>Last Login</th>
			</tr>
		</thead>
		<tbody>
		  <% @teachers.each do |teacher| %>
		  <tr>
				<td>
					<div class="table-sq i-<%= teacher.color %>">
						<span class="fa fa-<%= teacher.teacher_icon_name %> fa-2x table-icon"></span>
					</div>
				</td>
				<td><%= teacher.user_name %></td>
				<td><%= teacher.teacher_name %></td>
				<td><%= teacher.admin_powers %></td>
				<td><p class="listText"><span>FILL IN PROPER DATE</span></p></td>
>>>>>>> 7babec2b6a69c47d959fec45bc376a99d59b78de
      </tr>
      <% end %>
    </tbody>
    </thead>

app/views/teachers/new.html.erb
<div class="page-header cap17-header vertical-align">
  <div class="col-xs-11">
    <h2>New Teacher <small>- add a new teacher to TPTE</small></h2>
  </div>
  <div class="col-xs-1 ">
    <div class="header-sq i-ltblue" >
	  <span class="fa fa-home fa-3x teacher-icon "></span>
	</div>
  </div>
</div>

<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<!-- Teacher profile area -->
     	<!--<form class="form-horizontal">-->
     		
     		<!-- Teacher ID -->
     		<div class="row form-row">
    			<div class="col-sm-2 col-sm-offset-1"><h4> Teacher ID: </h4></div>
                <div class="col-sm-2">
    				<%= f.text_field :user_name %>
    			</div>
    		</div>
    		
    		<!-- Teacher name field -->
    		<div class="row form-row">
       		<div class="col-xs-1 col-xs-offset-1"><h4> Name: </h4></div>
       		<div class="col-xs-4 col-xs-offset-1">
    				<%= f.text_field :teacher_name %>
    			</div>
    		</div>   <!-- row -->
    		
    		<!-- Teacher Email -->
            <div class="row form-row">
    			<div class="col-sm-offset-1 col-sm-2"><h4> Email: </h4></div>
    
    			<div class="col-sm-4 col-sm-offset-0">
    				<%= f.text_field :teacher_email %>
   				</div>
    		</div>
    		
    		<!-- Teacher password -->
    		<div class="row form-row">
    			<div class="col-sm-offset-1 col-sm-2"><h4> Password: </h4></div>
    
    			<div class="col-sm-4 col-sm-offset-0">
    				<%= f.text_field :teacher_password %>
    			</div>
    		</div>
    		
    		<!-- Teacher Admin -->
            <div class="row form-row vertical-align">
    			<div class="col-sm-offset-3 col-sm-2"><h4> Admin </h4></div>
        		
                <%= f.check_box :admin_powers %>
        
        		<div class="col-sm-offset-0 col-sm-2"><h4> Analysis </h4></div>
         		
                <%= f.check_box :analysis_powers %>
    		</div>
    		
    		<!-- a little extra space after name/email -->
			<div class="form-spacer">	&nbsp;</div>
			
			<!-- Teacher Color -->
			<div class="row form-row vertical-align">
    			<div class="col-sm-offset-1 col-sm-2"><h4> Color: </h4></div>
    
    			<div class="col-sm-4 col-sm-offset-0">
    				<%= f.select :color, [ 'plum', 'red', 'yellow', 'cyan'], :prompt => 'Select One' %>
        	</div>
      </div>
       		
       		<!-- Teacher Icon Field -->
			<div class="row form-row">
				<div class="col-xs-1 col-xs-offset-1"><h4>Icon: </h4></div>
				<div class="col-xs-4 col-xs-offset-1">
					<%= f.select :teacher_icon_name, [ 'apple', 'graduationHat', 'book', 'pencil'], :prompt => 'Select One' %>
				</div>
			</div>
			
			<div class="row form-row">
    			<div class="col-sm-offset-1 col-sm-2"><h4>Description: </h4></div>
    
    			<div class="col-sm-6 col-sm-offset-0">
    				<%= f.text_area :teacher_description %>
    			</div>
    		</div>  
     
     		<div class="row form-row">
    			<div class="col-sm-1 col-sm-offset-1"><br></div>
    		</div>
    		
    		<div class="row action-buttons-row">
    			<div class="col-sm-1 col-sm-offset-1">
    				<%= f.submit %>
    			</div>
    			<div class="col-sm-1 col-sm-offset-1">
    				<%= link_to 'Cancel', teachers_path %>
    			</div>
  			</div>
<% end %>

<div class="row form-row">
	<div class="col-sm-1 col-sm-offset-1"><br></div>
</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @teacher.user_name %>
</p>

<p>
  <strong>Teacher icon name:</strong>
  <%= @teacher.teacher_icon_name %>
</p>

<p>
  <strong>Teacher name:</strong>
  <%= @teacher.teacher_name %>
</p>

<p>
  <strong>Teacher email:</strong>
  <%= @teacher.teacher_email %>
</p>

<p>
  <strong>Admin powers:</strong>
  <%= @teacher.admin_powers %>
</p>

<p>
  <strong>Analysis powers:</strong>
  <%= @teacher.analysis_powers %>
</p>

<p>
  <strong>Teacher description:</strong>
  <%= @teacher.teacher_description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @teacher.color %>
</p>

<p>
  <strong>School:</strong>
  <%= @teacher.school_id %>
</p>

<p>
  <strong>Teacher password:</strong>
  <%= @teacher.teacher_password %>
</p>

<p>
  <strong>Teacher password confirmation:</strong>
  <%= @teacher.teacher_password_confirmation %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/super_report.html.erb
<h1>Super Report</h1>
<h2>System report for the Super User</h2>
<p>Coming soon... stats about Dinner Out</p>
<p>@Session.session_event.count</p>
<p>@teacher.active_relationships.count</p>
<p>@teacher.students.count</p>
<%= Teacher.first.students.count %>
<%= Teacher.first.active_relationships.count %>
<%= link_to 'Return to Super Dashboard', schools_path %>