config/routes.rb
# Routes
# Team 1
# Author: Meagan Moore

Rails.application.routes.draw do
  root "login_session#new"
  
  get "teachers/:id/home",  to: 'teachers#home'

  resources :roster_students
  resources :roster_squares
  resources :session_events
  resources :sessions
  resources :squares
  resources :students
  resources :teachers
  resources :schools
  resources :login_session

  get    'login'   => 'login_session#new'
  post   'login'   => 'login_session#create'
  
  get    'logout'  => 'login_session#logout'
  
  get    'about1'  => 'static_pages#about1'
  get    'about2'  => 'static_pages#about2'
  
  get    'home1'   => 'static_pages#home1'
  post   'home1'   => 'static_pages#home1'

  resources :super
  get    '/super_report',    to: 'teachers#super_report'
  get    '/admin',    to: 'teachers#admin'
  #go back and make /super show the dashboard NOT /schools ... fix later.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roster_student.rb
class RosterStudent < ApplicationRecord
    belongs_to :teacher, class_name: "Teacher"
    belongs_to :student, class_name: "Student"
end

app/controllers/roster_students_controller.rb
class RosterStudentsController < ApplicationController
  before_action :set_roster_student, only: [:show, :edit, :update, :destroy]

  # GET /roster_students
  # GET /roster_students.json
  def index
    @roster_students = RosterStudent.all
  end

  # GET /roster_students/1
  # GET /roster_students/1.json
  def show
  end

  # GET /roster_students/new
  def new
    @roster_student = RosterStudent.new
  end

  # GET /roster_students/1/edit
  def edit
  end

  # POST /roster_students
  # POST /roster_students.json
  def create
    @roster_student = RosterStudent.new(roster_student_params)

    respond_to do |format|
      if @roster_student.save
        format.html { redirect_to @roster_student, notice: 'Roster student was successfully created.' }
        format.json { render :show, status: :created, location: @roster_student }
      else
        format.html { render :new }
        format.json { render json: @roster_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roster_students/1
  # PATCH/PUT /roster_students/1.json
  def update
    respond_to do |format|
      if @roster_student.update(roster_student_params)
        format.html { redirect_to @roster_student, notice: 'Roster student was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster_student }
      else
        format.html { render :edit }
        format.json { render json: @roster_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roster_students/1
  # DELETE /roster_students/1.json
  def destroy
    @roster_student.destroy
    respond_to do |format|
      format.html { redirect_to roster_students_url, notice: 'Roster student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster_student
      @roster_student = RosterStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_student_params
      params.require(:roster_student).permit(:student_id, :teacher_id)
    end
end

app/helpers/roster_students_helper.rb
module RosterStudentsHelper
end

app/views/roster_students/_form.html.erb
<%= form_for(roster_student) do |f| %>
  <% if roster_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roster_student.errors.count, "error") %> prohibited this roster_student from being saved:</h2>

      <ul>
      <% roster_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.number_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :teacher_id %>
    <%= f.number_field :teacher_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roster_students/edit.html.erb
<h1>Editing Roster Student</h1>

<%= render 'form', roster_student: @roster_student %>

<%= link_to 'Show', @roster_student %> |
<%= link_to 'Back', roster_students_path %>

app/views/roster_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roster Students</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roster_students.each do |roster_student| %>
      <tr>
        <td><%= roster_student.student_id %></td>
        <td><%= roster_student.teacher_id %></td>
        <td><%= link_to 'Show', roster_student %></td>
        <td><%= link_to 'Edit', edit_roster_student_path(roster_student) %></td>
        <td><%= link_to 'Destroy', roster_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster Student', new_roster_student_path %>

app/views/roster_students/new.html.erb
<h1>New Roster Student</h1>

<%= render 'form', roster_student: @roster_student %>

<%= link_to 'Back', roster_students_path %>

app/views/roster_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @roster_student.student_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @roster_student.teacher_id %>
</p>

<%= link_to 'Edit', edit_roster_student_path(@roster_student) %> |
<%= link_to 'Back', roster_students_path %>